# name: Build and Deploy to Server

#on:
#  push:
#    branches:
#      - main

#jobs:
#  build:
#    runs-on: ubuntu-latest

#    steps:
#      - name: Checkout code
#        uses: actions/checkout@v2

#      - name: Set up JDK 17
#        uses: actions/setup-java@v2
#        with:
#          distribution: 'temurin' # 설치할 JDK 배포판 (여기서는 Eclipse Temurin)
#          java-version: '17'

#      - name: Create .env file
#        run: |
#          echo "DATABASE_URL=${{ secrets.DATABASE_URL }}" >> .env
#          echo "DATABASE_USERNAME=${{ secrets.DATABASE_USERNAME }}" >> .env
#          echo "DATABASE_PASSWORD=${{ secrets.DATABASE_PASSWORD }}" >> .env

#      - name: Build with Gradle
#        run: ./gradlew build

  # EC2로 배포
#  deploy:
#    runs-on: ubuntu-latest
#    needs: build
#    steps:
#      - name: Checkout code
#        uses: actions/checkout@v2

#      - name: Set up SSH
#        uses: webfactory/ssh-agent@v0.5.3
#        with:
#          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

#      - name: Deploy Application to EC2
#        run: ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa ubuntu@13.209.91.95 "cd /home/ubuntu && ./deploy_swe9.sh"
        # EC2 서버에서 deploy.sh 실행